mutation addParkingAreaRate(
  $parkingAreaID: Int!
  $startTime: Time!
  $endTime: Time!
  $startDate: Date!
  $endDate: Date!
  $charge: Float!
) {
  addRate(
    parkingAreaID: $parkingAreaID
    startTime: $startTime
    endTime: $endTime
    startDate: $startDate
    endDate: $endDate
    charge: $charge
  ) {
    path
    message
  }
}
