mutation addUser(
  $role: String!
  $firstName: String!
  $lastName: String!
  $email: String!
  $personalNumber: String!
  $password: String!
) {
  registerUser(
    role: $role
    firstName: $firstName
    lastName: $lastName
    email: $email
    personalNumber: $personalNumber
    password: $password
  ) {
    firstName
    lastName
    email
    personalNumber
  }
}
