mutation editParkingArea(
  $id: Int!
  $name: String!
  $coordinates: [CoordinateInput]!
) {
  editParkingArea(
    id: $id
    name: $name
    coordinates: $coordinates
  ) {
    path
    message
  }
}

