query ($id: Int!){
    getParkingArea(id: $id){        
     id
     name
     coordinates {
      id
      latitude
      longitude
     }
     rates {
      startDate
      startTime
      endDate
      endTime
      charge
     }
     owner {
      id
     }  
    }
}