query {
  myInfo {
    id
    email
    roles {
      name
      admin
      addParkingAreaPermission
      editParkingAreaPermission
    }
    vehicles {
      registrationNumber
      id
    }
  }
}
