query {
  myInfo {
    id
    email
    roles {
      name
      admin
      addParkingAreaPermission
      editParkingAreaPermission
    }
    vehicles {
      registrationNumber
      id
    }
    currentParkingAreas {
      id
      name
      coordinates {
        id
        latitude
        longitude
      }
    }
  }
}
