---
- name: Remove frontend volume
  docker_volume:
    name: app_frontend
    state: absent

- name: Start docker compose
  docker_service:
    build: yes
    nocache: yes
    project_src: "{{ app_dir }}"
    files:
      - prod-docker-compose.yml
    state: present
  register: output
  tags:
    - deploy