version: "3"

services:
  nginx:
    build: nginx
    env_file:
      - .env.prod.local
    depends_on:
      - backend
      - frontend
    networks:
      - parkingapp
    ports:
      - 80:80
    volumes:
     - ./nginx/parkingapp_backend.conf:/etc/nginx/sites-enabled/default.conf
     - ./nginx/parkingapp_frontend.conf:/etc/nginx/sites-enabled/front.conf
     - frontend:/var/www/app/

  frontend:
    build:
      context: frontend
      dockerfile: Build.dockerfile
    env_file:
      - .env.prod.local
    volumes:
      - frontend:/opt/app/dist
      - /opt/app/node_modules

volumes:
  frontend: