---

- name: Create SG HTTP
  os_security_group:
    state: present
    name: HTTP
    description: Allows HTTP traffic to server

- name: Create SG SSH External
  os_security_group:
    state: present
    name: SSHExt
    description: Allows external SSH traffic to server

- name: Create SG SSH Internal
  os_security_group:
    state: present
    name: SSHInt
    description: Allows internal SSH traffic to server

- name: Create SG to allow port 81 (server) for demo
  os_security_group:
    state: present
    name: HTTP81
    description: Allows HTTP traffic on port 81

- name: Creating rules for SG HTTP
  os_security_group_rule:
    security_group: HTTP,HTTP81
    protocol: tcp
    port_range_min: 80
    port_range_max: 81
    remote_ip_prefix: 0.0.0.0/0

- name: Create rule for SG SSHExt
  os_security_group_rule:
    security_group: SSHExt
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

- name: Create rule for SG SSHInt
  os_security_group_rule:
    security_group: SSHInt
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: "{{ subnet }}"

# - name: Creating rules for SG HTTP 4000
#   os_security_group_rule:
#     security_group: HTTP4000
#     protocol: tcp
#     port_range_min: 4000
#     port_range_max: 4000
#     remote_ip_prefix: 0.0.0.0/0
