---
- name: Create app dir
  file:
    path: /opt/app
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  tags:
    - deploy

- name: Clone the repo to /opt/app
  git:
    repo: "{{ git_repo }}"
    dest: /opt/app
    accept_hostkey: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
    key_file: "{{ dest_deploy_key }}"
    version: release-production
    force: yes
  become_user: "{{ remote_user }}"
  become: true
  tags:
    - deploy

- name: Permissions on run_nginx.sh
  file:
    path: /opt/app/nginx/run_nginx.sh
    state: file
    mode: "a+x"

- name: Create env.prod.local file from vault
  template:
    src: .env.prod.local.j2
    dest: /opt/app/.env.local.prod