---

# - name: Create .ssh dir
#   file:
#     path: /home/ubuntu/.ssh
#     state: directory
#     owner: "{{ remote_user }}"
#     group: "{{ remote_user }}"
#   tags:
#     - deploy-key

- name: Copy the ssh key
  copy:
    content: "{{ deploy_key }}"
    dest: "{{ dest_deploy_key }}"
    mode: 0600
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
  tags:
    - deploy-key

# See: https://stackoverflow.com/a/37096534/100134
- name: Ensure setfacl support is present.
  package: name=acl
  tags:
    - deploy-key

- name: Test that deploy key exists
  stat:
    path: "{{ dest_deploy_key }}"
  register: key
  failed_when: key.stat.exists == False
  tags:
    - deploy-key