---

- name: Remove the ssh key
  file:
    path: "{{ dest_deploy_key }}"
    state: absent
  tags:
    - deploy-key

- name: Test that deploy key is absent
  stat:
    path: "{{ dest_deploy_key }}"
  register: key
  failed_when: key.stat.exists == True
  tags:
    - deploy-key