---

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip

- name: Install docker from pip
  pip:
    name: "{{item}}"
  with_items:
    - docker
    - docker-compose